// Recorded on Ubuntu 24.04 with PostgreSQL 18.6 and PgBouncer 1.26 from apt.postgresql.org,
// and on the postgres:18 Docker image. Generated by tools/postgres-capture/ops — do not edit by hand.

export const OPS = {
  "ubuntu": {
    "clusters": "$ pg_lsclusters\nVer Cluster Port Status Owner    Data directory              Log file\n18  main    5432 online postgres /var/lib/postgresql/18/main /var/log/postgresql/postgresql-18-main.log",
    "etc": "$ ls /etc/postgresql/18/main\nconf.d\nenvironment\npg_ctl.conf\npg_hba.conf\npg_ident.conf\npostgresql.conf\nstart.conf",
    "data": "$ ls /var/lib/postgresql/18/main\nPG_VERSION\nbase\nglobal\npg_commit_ts\npg_dynshmem\npg_logical\npg_multixact\npg_notify\npg_replslot\npg_serial\npg_snapshots\npg_stat\npg_stat_tmp\npg_subtrans\npg_tblspc\npg_twophase\npg_wal\npg_xact\npostgresql.auto.conf\npostmaster.opts\npostmaster.pid",
    "settings": "archive_mode|off\nconfig_file|/etc/postgresql/18/main/postgresql.conf\ndata_directory|/var/lib/postgresql/18/main\nhba_file|/etc/postgresql/18/main/pg_hba.conf\nlisten_addresses|localhost\nmax_connections|100\npassword_encryption|scram-sha-256\nport|5432\nshared_buffers|16384\nunix_socket_directories|/var/run/postgresql\nwal_level|replica",
    "hba": "local   all             postgres                                peer\nlocal   all             all                                     peer\nhost    all             all             127.0.0.1/32            scram-sha-256\nhost    all             all             ::1/128                 scram-sha-256\nlocal   replication     all                                     peer\nhost    replication     all             127.0.0.1/32            scram-sha-256\nhost    replication     all             ::1/128                 scram-sha-256"
  },
  "docker": "### old-mount\nError: in 18+, these Docker images are configured to store database data in a\n       format which is compatible with \"pg_ctlcluster\" (specifically, using\n       major-version-specific directory names).  This better reflects how\n       PostgreSQL itself works, and how upgrades are to be performed.\n\n       See also https://github.com/docker-library/postgres/pull/1259\n\n       Counter to that, there appears to be PostgreSQL data in:\n         /var/lib/postgresql/data (unused mount/volume)\n\n       This is usually the result of upgrading the Docker image without\n       upgrading the underlying database using \"pg_upgrade\" (which requires both\n       versions).\n### new-mount\n$ ls /var/lib/postgresql\n18\n$ psql -U postgres -Atc \"SHOW data_directory\"\n/var/lib/postgresql/18/docker",
  "setup": {
    "refused": "client$ psql \"host=10.0.1.10 dbname=shop user=app_rw\" -c \"SELECT 1\"\npsql: error: connection to server at \"10.0.1.10\", port 5432 failed: Connection refused\n\tIs the server running on that host and accepting TCP/IP connections?",
    "alter": {
      "pending": "       name       |  setting  | unit | pending_restart \n------------------+-----------+------+-----------------\n listen_addresses | localhost |      | t\n shared_buffers   | 16384     | 8kB  | t\n(2 rows)",
      "autoConf": "# Do not edit this file manually!\n# It will be overwritten by the ALTER SYSTEM command.\nlisten_addresses = '*'\nshared_buffers = '512MB'",
      "restarted": "       name       | setting | unit | pending_restart \n------------------+---------+------+-----------------\n listen_addresses | *       |      | f\n shared_buffers   | 65536   | 8kB  | f\n(2 rows)"
    },
    "hbaReject": "client$ psql \"host=10.0.1.10 dbname=shop user=app_rw\" -c \"SELECT 1\"\npsql: error: connection to server at \"10.0.1.10\", port 5432 failed: FATAL:  no pg_hba.conf entry for host \"10.0.1.20\", user \"app_rw\", database \"shop\", SSL encryption\nconnection to server at \"10.0.1.10\", port 5432 failed: FATAL:  no pg_hba.conf entry for host \"10.0.1.20\", user \"app_rw\", database \"shop\", no encryption",
    "hbaRules": " line_number | type  |   database    | user_name  |  address  |                 netmask                 |  auth_method  | error \n-------------+-------+---------------+------------+-----------+-----------------------------------------+---------------+-------\n         118 | local | {all}         | {postgres} |           |                                         | peer          | \n         123 | local | {all}         | {all}      |           |                                         | peer          | \n         125 | host  | {all}         | {all}      | 127.0.0.1 | 255.255.255.255                         | scram-sha-256 | \n         127 | host  | {all}         | {all}      | ::1       | ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff | scram-sha-256 | \n         130 | local | {replication} | {all}      |           |                                         | peer          | \n         131 | host  | {replication} | {all}      | 127.0.0.1 | 255.255.255.255                         | scram-sha-256 | \n         132 | host  | {replication} | {all}      | ::1       | ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff | scram-sha-256 | \n         133 | host  | {shop}        | {app_rw}   | 10.0.1.0  | 255.255.255.0                           | scram-sha-256 | \n(8 rows)",
    "privileges": "                                        Access privileges\n Schema |     Name      |   Type   |      Access privileges       | Column privileges | Policies \n--------+---------------+----------+------------------------------+-------------------+----------\n app    | orders        | table    | app_owner=arwdDxtm/app_owner+|                   | \n        |               |          | app_rw=arwd/app_owner        |                   | \n app    | orders_id_seq | sequence | app_owner=rwU/app_owner     +|                   | \n        |               |          | app_rw=U/app_owner           |                   | \n(2 rows)",
    "appOk": "client$ psql \"host=10.0.1.10 dbname=shop user=app_rw\" -c \"INSERT INTO app.orders (amount) VALUES (25.00) RETURNING id, (SELECT inet_client_addr()) AS client\"\n id |  client   \n----+-----------\n  1 | 10.0.1.20\n(1 row)\n\nINSERT 0 1",
    "denied": [
      "client$ psql \"host=10.0.1.10 dbname=shop user=app_rw\" -c \"DROP TABLE app.orders\"\nERROR:  must be owner of table orders\n",
      "client$ psql \"host=10.0.1.10 dbname=shop user=app_rw\" -c \"CREATE TABLE app.audit (id int)\"\nERROR:  permission denied for schema app\nLINE 1: CREATE TABLE app.audit (id int)\n                     ^\n",
      "client$ psql \"host=10.0.1.10 dbname=postgres user=app_rw\" -c \"SELECT 1\"\npsql: error: connection to server at \"10.0.1.10\", port 5432 failed: FATAL:  no pg_hba.conf entry for host \"10.0.1.20\", user \"app_rw\", database \"postgres\", SSL encryption\nconnection to server at \"10.0.1.10\", port 5432 failed: FATAL:  no pg_hba.conf entry for host \"10.0.1.20\", user \"app_rw\", database \"postgres\", no encryption\n",
      "client$ psql \"host=10.0.1.10 dbname=shop user=app_rw\" -c \"SELECT 1\"\npsql: error: connection to server at \"10.0.1.10\", port 5432 failed: FATAL:  password authentication failed for user \"app_rw\"\nconnection to server at \"10.0.1.10\", port 5432 failed: FATAL:  password authentication failed for user \"app_rw\""
    ],
    "log": "2026-10-10 06:39:51.125 UTC [83] app_rw@shop FATAL:  password authentication failed for user \"app_rw\"\n2026-10-10 06:39:51.125 UTC [83] app_rw@shop DETAIL:  Connection matched file \"/etc/postgresql/18/main/pg_hba.conf\" line 133: \"host    shop            app_rw          10.0.1.0/24             scram-sha-256\""
  },
  "pool": {
    "queue": {
      "during": {
        "database": "shop",
        "cl_active": 2,
        "cl_waiting": 3,
        "sv_active": 2,
        "sv_idle": 0,
        "pool_mode": "transaction"
      },
      "results": [
        {
          "client": 1,
          "backend": 103,
          "doneAfterMs": 1003,
          "doneAfterS": 1
        },
        {
          "client": 2,
          "backend": 104,
          "doneAfterMs": 1004,
          "doneAfterS": 1
        },
        {
          "client": 3,
          "backend": 103,
          "doneAfterMs": 2005,
          "doneAfterS": 2
        },
        {
          "client": 4,
          "backend": 104,
          "doneAfterMs": 2005,
          "doneAfterS": 2
        },
        {
          "client": 5,
          "backend": 103,
          "doneAfterMs": 3007,
          "doneAfterS": 3
        }
      ],
      "after": {
        "database": "shop",
        "cl_active": 5,
        "cl_waiting": 0,
        "sv_active": 0,
        "sv_idle": 2,
        "pool_mode": "transaction"
      }
    },
    "leak": [
      {
        "who": "A",
        "sql": "SHOW statement_timeout",
        "result": "0"
      },
      {
        "who": "A",
        "sql": "SET statement_timeout = '5s'",
        "result": "SET"
      },
      {
        "who": "B",
        "sql": "SHOW statement_timeout",
        "result": "5s"
      },
      {
        "who": "B",
        "sql": "RESET statement_timeout",
        "result": "RESET"
      },
      {
        "who": "A",
        "sql": "BEGIN; SET LOCAL statement_timeout = '5s'; COMMIT",
        "result": "COMMIT"
      },
      {
        "who": "B",
        "sql": "SHOW statement_timeout",
        "result": "0"
      },
      {
        "who": "A",
        "sql": "SELECT pg_backend_pid()",
        "result": "105"
      },
      {
        "who": "B",
        "sql": "SELECT pg_backend_pid()",
        "result": "105"
      }
    ],
    "session": {
      "during": {
        "database": "shop_session",
        "cl_active": 2,
        "cl_waiting": 1,
        "sv_active": 2,
        "sv_idle": 0,
        "pool_mode": "session"
      },
      "waitedS": 2,
      "after": {
        "database": "shop_session",
        "cl_active": 2,
        "cl_waiting": 0,
        "sv_active": 2,
        "sv_idle": 0,
        "pool_mode": "session"
      }
    },
    "prepared": [
      {
        "client": 1,
        "round": 1,
        "n": 1,
        "pid": 103
      },
      {
        "client": 2,
        "round": 1,
        "n": 1,
        "pid": 103
      },
      {
        "client": 3,
        "round": 1,
        "n": 1,
        "pid": 103
      },
      {
        "client": 1,
        "round": 2,
        "n": 1,
        "pid": 103
      },
      {
        "client": 2,
        "round": 2,
        "n": 1,
        "pid": 103
      },
      {
        "client": 3,
        "round": 2,
        "n": 1,
        "pid": 103
      }
    ]
  },
  "backup": {
    "archive": "archive_command|test ! -f /backup/wal/%f && cp %p /backup/wal/%f\narchive_mode|on\nsummarize_wal|on\nwal_level|replica",
    "dumpList": "$ pg_restore --list /backup/shop.dump | grep -v '^;' | grep -v '^$'\n6; 2615 16387 SCHEMA - app app_owner\n3430; 0 0 ACL - SCHEMA app app_owner\n221; 1259 16391 TABLE app orders app_owner\n3431; 0 0 ACL app TABLE orders app_owner\n220; 1259 16390 SEQUENCE app orders_id_seq app_owner\n3432; 0 0 SEQUENCE OWNED BY app orders_id_seq app_owner\n3433; 0 0 ACL app SEQUENCE orders_id_seq app_owner\n3272; 2604 16394 DEFAULT app orders id app_owner\n3423; 0 16391 TABLE DATA app orders app_owner\n3434; 0 0 SEQUENCE SET app orders_id_seq app_owner\n3274; 2606 16398 CONSTRAINT app orders orders_pkey app_owner\n2054; 826 16389 DEFAULT ACL app DEFAULT PRIVILEGES FOR SEQUENCES app_owner\n2053; 826 16388 DEFAULT ACL app DEFAULT PRIVILEGES FOR TABLES app_owner",
    "globals": "$ pg_dumpall --globals-only | grep -E '^(CREATE|ALTER) ROLE'\nCREATE ROLE app_owner;\nALTER ROLE app_owner WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB NOLOGIN NOREPLICATION NOBYPASSRLS;\nCREATE ROLE app_rw;\nALTER ROLE app_rw WITH NOSUPERUSER INHERIT NOCREATEROLE NOCREATEDB LOGIN NOREPLICATION NOBYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:…';\nCREATE ROLE postgres;\nALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS;",
    "copy": "$ createdb shop_copy && pg_restore -d shop_copy /backup/shop.dump && psql -d shop_copy -Atc 'SELECT count(*) FROM app.orders'\n1",
    "full": "$ pg_basebackup -D /backup/base/full -c fast -P\nwaiting for checkpoint\n   84/39264 kB (0%), 0/1 tablespace\n39275/39275 kB (100%), 0/1 tablespace\n39275/39275 kB (100%), 1/1 tablespace",
    "label": "$ cat /backup/base/full/backup_label\nSTART WAL LOCATION: 0/3000028 (file 000000010000000000000003)\nCHECKPOINT LOCATION: 0/3000080\nBACKUP METHOD: streamed\nBACKUP FROM: primary\nSTART TIME: 2026-10-10 06:41:23 UTC\nLABEL: pg_basebackup base backup\nSTART TIMELINE: 1",
    "verify": "$ /usr/lib/postgresql/18/bin/pg_verifybackup /backup/base/full\nbackup successfully verified\n$ /usr/lib/postgresql/18/bin/pg_verifybackup /backup/base/incr1\nbackup successfully verified",
    "du": "$ du -sh /backup/base/full /backup/base/incr1\n54M\t/backup/base/full\n26M\t/backup/base/incr1",
    "rows": "1|25.00\n2|10.00\n3|20.00\n4|30.00",
    "goodTime": "2026-10-10 06:41:27+00",
    "accidentTime": "2026-10-10 06:41:29+00",
    "archived": "8|000000010000000000000006|0",
    "walList": "$ ls /backup/wal\n000000010000000000000001\n000000010000000000000002\n000000010000000000000003\n000000010000000000000003.00000028.backup\n000000010000000000000004\n000000010000000000000005\n000000010000000000000005.00000028.backup\n000000010000000000000006",
    "combine": "$ /usr/lib/postgresql/18/bin/pg_combinebackup /backup/base/full /backup/base/incr1 -o /var/lib/postgresql/18/main",
    "recoveryConf": "$ cat /etc/postgresql/18/main/conf.d/recovery.conf\nrestore_command = 'cp /backup/wal/%f %p'\nrecovery_target_time = '2026-10-10 06:41:27+00'\nrecovery_target_action = 'promote'",
    "log": "06:41:49.871 UTC [291] LOG:  database system was interrupted; last known up at 2026-10-10 06:41:25 UTC\ncp: cannot stat '/backup/wal/00000002.history': No such file or directory\n06:41:49.915 UTC [291] LOG:  starting backup recovery with redo LSN 0/5000028, checkpoint LSN 0/5000080, on timeline ID 1\n06:41:49.919 UTC [291] LOG:  restored log file \"000000010000000000000005\" from archive\n06:41:49.923 UTC [291] LOG:  starting point-in-time recovery to 2026-10-10 06:41:27+00\n06:41:49.927 UTC [291] LOG:  redo starts at 0/5000028\n06:41:49.931 UTC [291] LOG:  restored log file \"000000010000000000000006\" from archive\ncp: cannot stat '/backup/wal/000000010000000000000007': No such file or directory\n06:41:49.938 UTC [291] LOG:  completed backup recovery with redo LSN 0/5000028 and end LSN 0/5000120\n06:41:49.938 UTC [291] LOG:  consistent recovery state reached at 0/5000120\n06:41:49.938 UTC [285] LOG:  database system is ready to accept read-only connections\n06:41:49.938 UTC [291] LOG:  recovery stopping before commit of transaction 791, time 2026-10-10 06:41:29.782844+00\n06:41:49.938 UTC [291] LOG:  redo done at 0/600AD38 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.01 s\n06:41:49.938 UTC [291] LOG:  last completed transaction was at log time 2026-10-10 06:41:26.562617+00\n06:41:49.943 UTC [291] LOG:  restored log file \"000000010000000000000006\" from archive\ncp: cannot stat '/backup/wal/00000002.history': No such file or directory\n06:41:49.951 UTC [291] LOG:  selected new timeline ID: 2\ncp: cannot stat '/backup/wal/00000001.history': No such file or directory\n06:41:49.984 UTC [291] LOG:  archive recovery complete\n06:41:49.986 UTC [289] LOG:  checkpoint starting: end-of-recovery immediate wait\n06:41:50.013 UTC [285] LOG:  database system is ready to accept connections",
    "result": "1|25.00\n2|10.00\n3|20.00\n4|30.00\nf|2",
    "history": "$ cat /backup/wal/00000002.history\n1\t0/600AD38\tbefore 2026-10-10 06:41:29.782844+00\n"
  }
} as const
