import { readFileSync, writeFileSync } from 'node:fs'
const [, , outDir] = process.argv
const scenarios = JSON.parse(readFileSync('scenarios.json', 'utf8'))
const capture = JSON.parse(readFileSync('capture.json', 'utf8'))
const ps = readFileSync('ps.txt', 'utf8').trimEnd()
const header = '// Recorded from PostgreSQL 18.6 (two real sessions, pageinspect / pg_walinspect).\n// Generated by tools/postgres-capture — do not edit by hand.\n\n'
const trimmed = Object.fromEntries(scenarios.map((s) => [s.name, s.frames.map((f) => ({
  step: f.step ? { s: f.step.s, sql: f.step.sql } : null,
  results: f.results,
  sessions: f.sessions,
  page: f.page.map((t) => Object.fromEntries(Object.entries(t).filter(([k]) => k !== 'xmax_invalid_hint'))),
  xids: f.xids,
}))]))
writeFileSync(`${outDir}/scenarios.ts`, header + `import type { Scenario } from './types'\n\nexport const SCENARIOS: Record<string, Scenario> = ${JSON.stringify(trimmed)}\n`)
writeFileSync(`${outDir}/captures.ts`, header + `export const POSTGRES_VERSION = 'PostgreSQL 18.6'\n\nexport const PROCESSES = ${JSON.stringify(ps)}\n\nexport const CAPTURE = ${JSON.stringify(capture)} as const\n`)
