// Turns the recorded transcripts into src/modules/postgres/data/ops.ts.
import { readFileSync, writeFileSync } from 'node:fs'
const [, , outFile] = process.argv
const sections = (file) => {
  const out = {}
  let name = null
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    const m = line.match(/^### (.+)$/)
    if (m) { name = m[1]; out[name] = []; continue }
    if (name) out[name].push(line)
  }
  return Object.fromEntries(Object.entries(out).map(([k, v]) => [k, v.join('\n').replace(/\n{3,}/g, '\n\n').trim()]))
}
const blocks = (text) => text.split(/\n(?=\$ |client\$ )/) // one command and its output per block
const ubuntu = readFileSync('ubuntu.txt', 'utf8').split(/\n(?=\$ )/).map((b) => b.trim())
const pick = (prefix) => ubuntu.find((b) => b.startsWith(`$ ${prefix}`))
const setup = sections('setup.txt')
const backup = sections('backup.txt')
const restore = sections('restore.txt')
const docker = readFileSync('docker.txt', 'utf8').trim()
const pool = JSON.parse(readFileSync('pool.json', 'utf8'))

const ops = {
  ubuntu: {
    clusters: ubuntu.filter((b) => b.startsWith('$ pg_lsclusters')).at(-1),
    etc: pick('ls /etc/postgresql'),
    data: pick('ls /var/lib/postgresql'),
    settings: ubuntu.find((b) => b.includes('pg_settings')).split('\n').slice(1).join('\n'),
    hba: pick('grep').split('\n').slice(1).join('\n'),
  },
  docker,
  setup: {
    refused: setup['listen-refused'],
    alter: (() => {
      const t = setup['alter-system']
      const tables = t.split(/\n(?=       name)/).slice(1).map((x) => x.slice(0, x.indexOf('(2 rows)') + 8))
      return { pending: tables[0], autoConf: t.slice(t.indexOf('# Do not edit'), t.indexOf("'512MB'") + 7), restarted: tables[1] }
    })(),
    hbaReject: setup['hba-reject'],
    hbaRules: setup['hba-add'].split('\n').slice(1).join('\n'),
    privileges: setup.roles.slice(setup.roles.indexOf('                                        Access privileges')),
    appOk: setup['app-ok'],
    denied: blocks(setup['app-denied']),
    log: setup.log.split('\n').filter((l) => l.includes('password authentication') || l.includes('DETAIL')).slice(0, 2).join('\n'),
  },
  pool,
  backup: {
    archive: backup['archive-config'].split('\n').filter((l) => l.includes('|')).join('\n'),
    dumpList: blocks(backup.dump)[1],
    globals: blocks(backup.dump)[2].replace(/SCRAM-SHA-256\$[^']+/, 'SCRAM-SHA-256$4096:…'),
    copy: blocks(backup.dump)[3],
    full: blocks(backup.full)[0],
    label: blocks(backup.full)[1],
    verify: restore.verify,
    du: blocks(backup.incremental)[1],
    rows: backup.good.split('\n').filter((l) => /^\d\|/.test(l)).slice(1).join('\n'),
    goodTime: backup.good.match(/good point: (.+)/)[1],
    accidentTime: backup.accident.split('\n')[0],
    archived: backup.accident.split('\n').find((l) => /^\d+\|/.test(l)),
    walList: blocks(backup.accident).at(-1),
    combine: blocks(restore.restore)[0],
    recoveryConf: blocks(restore.restore)[1],
    log: restore['recovery-log'].split('\n').filter((l) => !l.includes('listening on') && !l.includes('starting PostgreSQL') && !l.includes('checkpoint complete')).map((l) => l.replace(/^2026-10-10 /, '')).join('\n'),
    result: restore.result.split('\n').slice(0, 5).join('\n'),
    history: blocks(restore.result).find((b) => b.startsWith('$ cat')),
  },
}
const header = '// Recorded on Ubuntu 24.04 with PostgreSQL 18.6 and PgBouncer 1.26 from apt.postgresql.org,\n// and on the postgres:18 Docker image. Generated by tools/postgres-capture/ops — do not edit by hand.\n\n'
writeFileSync(outFile, `${header}export const OPS = ${JSON.stringify(ops, null, 2)} as const\n`)
console.log(Object.keys(ops.setup), ops.backup.goodTime, '|', ops.backup.accidentTime, '|', ops.backup.archived)
