export interface GlossaryEntry {
  term: string
  definition: string
  /** Lesson slug where the term is explained. */
  lesson: string
}

export const GLOSSARY: GlossaryEntry[] = [
  { term: 'acks', definition: 'Producer setting for how many replicas must store a record before the write counts as successful: 0, 1 or all.', lesson: 'producers' },
  { term: 'Active segment', definition: 'The newest segment file of a partition; the only one that receives writes and is never deleted by retention.', lesson: 'retention' },
  { term: 'Assignor', definition: 'Strategy that decides which partitions each member of a consumer group gets (range, round robin, sticky, cooperative-sticky).', lesson: 'consumer-groups' },
  { term: 'At-least-once', definition: 'Delivery guarantee where nothing is lost but records may be processed more than once. Process, then commit.', lesson: 'delivery' },
  { term: 'At-most-once', definition: 'Delivery guarantee where records are never processed twice but may be lost. Commit, then process.', lesson: 'delivery' },
  { term: 'auto.offset.reset', definition: 'Where a consumer starts when its group has no committed offset: earliest, latest, none, or (Kafka 4.0+) by_duration:<ISO duration>.', lesson: 'offsets' },
  { term: 'Batch', definition: 'Records for the same partition grouped and sent together by the producer.', lesson: 'producers' },
  { term: 'bootstrap.servers', definition: 'Initial broker addresses a client contacts to discover the rest of the cluster.', lesson: 'brokers' },
  { term: 'Broker', definition: 'A Kafka server process that stores partition data and serves clients.', lesson: 'brokers' },
  { term: 'CDC', definition: 'Change data capture: turning every database insert, update and delete into an event.', lesson: 'debezium' },
  { term: 'Change event', definition: 'Debezium record describing a row change, with before, after, source, op and ts_ms.', lesson: 'debezium' },
  { term: 'cleanup.policy', definition: 'Topic setting choosing delete (retention), compact, or both.', lesson: 'retention' },
  { term: 'Cluster', definition: 'Brokers and controllers working together as one Kafka system.', lesson: 'brokers' },
  { term: 'Commit', definition: 'Saving a consumer group’s position in a partition so it can resume there later.', lesson: 'delivery' },
  { term: 'Committed offset', definition: 'The saved offset a group will resume from after a restart or rebalance.', lesson: 'offsets' },
  { term: 'Compaction', definition: 'Cleanup that keeps only the latest record per key.', lesson: 'retention' },
  { term: 'Config provider', definition: 'Kafka Connect mechanism that resolves placeholders like ${file:path:key} so secrets stay out of configs.', lesson: 'kafka-connect' },
  { term: 'Connector', definition: 'A configured Kafka Connect plugin instance that copies data into (source) or out of (sink) Kafka.', lesson: 'kafka-connect' },
  { term: 'Consumer', definition: 'An application that reads records from Kafka topics.', lesson: 'consumer-groups' },
  { term: 'Consumer group', definition: 'Consumers sharing a group.id that divide a topic’s partitions between them.', lesson: 'consumer-groups' },
  { term: 'Consumer lag', definition: 'Log-end offset minus committed offset: how far behind a group is.', lesson: 'offsets' },
  { term: '__consumer_offsets', definition: 'Internal compacted topic storing committed offsets for every group.', lesson: 'offsets' },
  { term: 'Controller', definition: 'Node managing cluster metadata and electing partition leaders.', lesson: 'brokers' },
  { term: 'Converter', definition: 'Kafka Connect component translating between structured data and bytes (String, JSON, Avro…).', lesson: 'kafka-connect' },
  { term: 'Dead letter queue', definition: 'A topic where records that cannot be processed are sent for inspection.', lesson: 'delivery' },
  { term: 'Debezium', definition: 'Open-source CDC platform implemented as Kafka Connect source connectors.', lesson: 'debezium' },
  { term: 'Deserializer', definition: 'Consumer component that turns bytes back into objects.', lesson: 'events' },
  { term: 'Dual write', definition: 'Writing to two systems without a shared transaction, risking inconsistency.', lesson: 'outbox' },
  { term: 'Event', definition: 'An immutable fact that something happened.', lesson: 'why-kafka' },
  { term: 'Exactly-once', definition: 'Each record’s effect happens once; achieved with Kafka transactions, or at-least-once plus idempotent processing.', lesson: 'delivery' },
  { term: 'Follower', definition: 'A replica that copies a partition from its leader.', lesson: 'replication' },
  { term: 'Generation', definition: 'Counter incremented on each rebalance; fences off stale group members.', lesson: 'consumer-groups' },
  { term: 'Group coordinator', definition: 'Broker that manages a consumer group’s membership and offset commits.', lesson: 'consumer-groups' },
  { term: 'Header', definition: 'Optional key/value metadata attached to a record.', lesson: 'events' },
  { term: 'Heartbeat (consumer)', definition: 'Periodic signal from a group member to the coordinator proving it is alive.', lesson: 'consumer-groups' },
  { term: 'Heartbeat (Debezium)', definition: 'Periodic record that lets Debezium commit its position, so the replication slot advances on quiet tables.', lesson: 'debezium' },
  { term: 'High watermark', definition: 'Highest offset replicated to all in-sync replicas; consumers only read below it.', lesson: 'replication' },
  { term: 'Idempotent consumer', definition: 'A handler for which processing a record twice has the same effect as once.', lesson: 'delivery' },
  { term: 'Idempotent producer', definition: 'Producer that numbers its batches so retries never create duplicates.', lesson: 'producers' },
  { term: 'ISR', definition: 'In-sync replicas: the leader and every follower fully caught up with it.', lesson: 'replication' },
  { term: 'Key', definition: 'Optional record identifier; equal keys go to the same partition and stay ordered.', lesson: 'events' },
  { term: 'KRaft', definition: 'Kafka’s built-in Raft-based metadata quorum, replacing ZooKeeper.', lesson: 'brokers' },
  { term: 'Leader', definition: 'The replica that handles all reads and writes for a partition.', lesson: 'replication' },
  { term: 'linger.ms', definition: 'How long a producer waits to fill a batch before sending it.', lesson: 'producers' },
  { term: 'Listener', definition: 'A network endpoint a broker accepts connections on; advertised listeners are what clients are told to use.', lesson: 'brokers' },
  { term: 'Log', definition: 'An ordered, append-only sequence of records.', lesson: 'why-kafka' },
  { term: 'Log-end offset', definition: 'The offset the next record written to a partition will receive.', lesson: 'offsets' },
  { term: 'Logical replication slot', definition: 'Postgres cursor over decoded WAL that retains it until the reader confirms.', lesson: 'debezium' },
  { term: 'LSN', definition: 'Log sequence number: a position in the Postgres WAL.', lesson: 'debezium' },
  { term: 'max.poll.interval.ms', definition: 'Longest allowed gap between poll() calls before a consumer is removed from its group.', lesson: 'consumer-groups' },
  { term: 'min.insync.replicas', definition: 'Minimum number of in-sync replicas required to accept an acks=all write.', lesson: 'replication' },
  { term: 'murmur2', definition: 'Hash function the default partitioner applies to key bytes.', lesson: 'producers' },
  { term: 'Offset', definition: 'Sequential position of a record within one partition.', lesson: 'offsets' },
  { term: 'Outbox', definition: 'Table where events are written in the same transaction as business data, then relayed to Kafka.', lesson: 'outbox' },
  { term: 'Partition', definition: 'One ordered log within a topic; the unit of parallelism, ordering and replication.', lesson: 'topics-partitions' },
  { term: 'Partitioner', definition: 'Producer component that chooses a record’s partition.', lesson: 'producers' },
  { term: 'pgoutput', definition: 'Postgres’ built-in logical decoding plugin used by Debezium.', lesson: 'debezium' },
  { term: 'Poison pill', definition: 'A record that fails every time it is processed.', lesson: 'delivery' },
  { term: 'Predicate', definition: 'Condition deciding whether a Connect transform applies to a record.', lesson: 'kafka-connect' },
  { term: 'Producer', definition: 'An application that writes records to Kafka.', lesson: 'producers' },
  { term: 'Publication', definition: 'Postgres object listing the tables included in logical replication.', lesson: 'debezium' },
  { term: 'Rebalance', definition: 'Reassignment of partitions among group members when membership changes.', lesson: 'consumer-groups' },
  { term: 'Record', definition: 'A stored event: key, value, headers, timestamp and offset.', lesson: 'events' },
  { term: 'Replica', definition: 'A copy of a partition on one broker.', lesson: 'replication' },
  { term: 'Replication factor', definition: 'Number of replicas of each partition in a topic.', lesson: 'replication' },
  { term: 'Retention', definition: 'How long or how much data a topic keeps before old segments are deleted.', lesson: 'retention' },
  { term: 'Schema Registry', definition: 'Service storing record schemas so producers and consumers agree on formats.', lesson: 'events' },
  { term: 'Segment', definition: 'File holding a contiguous range of a partition’s records.', lesson: 'retention' },
  { term: 'Serializer', definition: 'Producer component that turns objects into bytes.', lesson: 'events' },
  { term: 'session.timeout.ms', definition: 'Time without heartbeats after which a consumer is considered dead.', lesson: 'consumer-groups' },
  { term: 'Sink connector', definition: 'Connector that reads from Kafka and writes to an external system.', lesson: 'kafka-connect' },
  { term: 'SMT', definition: 'Single Message Transform: lightweight per-record change applied by Kafka Connect.', lesson: 'kafka-connect' },
  { term: 'Snapshot', definition: 'Debezium’s initial read of existing rows before streaming changes.', lesson: 'debezium' },
  { term: 'Source connector', definition: 'Connector that reads from an external system and writes into Kafka.', lesson: 'kafka-connect' },
  { term: 'Static membership', definition: 'Stable group.instance.id so a consumer that restarts within session.timeout.ms keeps its partitions without a rebalance.', lesson: 'consumer-groups' },
  { term: 'Sticky partitioning', definition: 'For key-less records, send to one partition until about batch.size bytes have gone to it, then switch.', lesson: 'producers' },
  { term: 'Task', definition: 'Unit of parallel work inside a Kafka Connect connector.', lesson: 'kafka-connect' },
  { term: 'Tombstone', definition: 'A record with a null value marking its key as deleted in a compacted topic.', lesson: 'retention' },
  { term: 'Topic', definition: 'A named stream of records split into partitions.', lesson: 'topics-partitions' },
  { term: 'Transaction (Kafka)', definition: 'Atomic write across partitions, visible all-or-nothing to read_committed consumers.', lesson: 'producers' },
  { term: 'Unclean leader election', definition: 'Electing an out-of-sync replica as leader; restores availability but loses data.', lesson: 'replication' },
  { term: 'Value', definition: 'The payload bytes of a record.', lesson: 'events' },
  { term: 'WAL', definition: 'Write-ahead log: Postgres’ ordered, durable record of every change.', lesson: 'debezium' },
  { term: 'Worker', definition: 'JVM process running Kafka Connect connectors and tasks.', lesson: 'kafka-connect' },
  { term: 'ZooKeeper', definition: 'External coordination service older Kafka versions needed; removed in Kafka 4.0.', lesson: 'brokers' },
]
